film/urls.py
from django.urls import path

from . import views

app_name = 'film' 

urlpatterns = [
     path("", views.homepage_view, name="homepage"),
     
     path('ajouter_commentaire/<int:film_id>/', views.ajouter_commentaire, name='ajouter_commentaire'),
     
     path('creer_collection/', views.creer_collection, name='creer_collection'),
    path('liste_collections/', views.liste_collections, name='liste_collections'),
    path('supprimer_collection/<str:nom>/', views.supprimer_collection, name='supprimer_collection'),

     path('ajouter_film/<int:film_id>/', views.ajouter_film, name='ajouter_film'),
    path('liste_films_panier/', views.liste_films_panier, name='liste_films_panier'),
    path('supprimer_films_panier/<int:film_id>/', views.supprimer_film_panier, name='supprimer_film_panier'),
    
     path('<int:film_id>/', views.film_detail, name='film_detail'),
     path('search/', views.search, name='movie_search'),
]

film_recommender/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include('registration.urls', namespace='reg')),
    path("film/", include('film.urls', namespace='film')),
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import path

from . import views

app_name = 'reg' 

urlpatterns = [
    #  path("", views.login_page, name="newuser"),
    path("logout/", views.logout_user, name="logout"),
    path("login/", views.login_user, name="login"),
    path('register/', views.inscription, name='register'),
     
]

film/models.py
from django.db import models
from registration.models import User

class Utilisateur(models.Model):
    username = models.CharField(max_length=50)
    nomut = models.CharField(max_length=50)
    ageut = models.IntegerField()
    code = models.CharField(max_length=50)
    genreut = models.CharField(max_length=50)
    role = models.CharField(max_length=2)
    date_ut = models.DateField()
    

class FilmSerie(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    description = models.CharField(max_length=5000, null=True, default="Unavailable")
    datef = models.DateField(null=True)
    langue = models.CharField(max_length=10, null=True)
    j_aime = models.IntegerField(null=True, default=0)
    j_aime_pas = models.IntegerField(null=True, default=0)
    note = models.DecimalField(max_digits=3, decimal_places=1, null=True, default=0)
    poster_path = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title
    
class Panier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    films = models.ManyToManyField(FilmSerie, related_name='panier')
    
    
    
class Collection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=255)
    films = models.ManyToManyField(FilmSerie)
    date_creation = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'nom')
        
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(FilmSerie, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')


    def __str__(self):
        return f"{self.user.username} - {self.film.titre}"
    
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(FilmSerie, on_delete=models.CASCADE, related_name='ratings')
    stars = models.IntegerField(default=0, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'film',)

film/forms.py
from django import forms

class CollectionCreationForm(forms.Form):
    name = forms.CharField(label='Search', max_length=100)
    
class RatingForm(forms.Form):
    stars = forms.IntegerField(label='Nombre d\'étoiles', min_value=1, max_value=5, widget=forms.TextInput(attrs={'type': 'range', 'class': 'form-range', 'min': 1, 'max': 5}))

film/views.py
from django.contrib import messages
from urllib import response
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from .api import get_movies, get_movies_details, add_movies
from .forms import CollectionCreationForm, RatingForm
from .models import FilmSerie, Panier, Collection, Comment, Rating
from.recommender import movie_recommender, user_movie_recommender

from django.db.models import Avg


import requests
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def homepage_view(request):
    # add_movies()
    films = FilmSerie.objects.all().order_by('note')

    
    # nombre d'éléments par page
    elements_par_page = 106

    # créer un objet Paginator avec la liste et le nombre d'éléments par page
    paginator = Paginator(films, elements_par_page)

    # obtenir le numéro de page à afficher
    page = request.GET.get('page')
    
    print(page)

    try:
        # obtenir les éléments pour la page courante
        elements = paginator.get_page(page)
    except PageNotAnInteger:
        # If page is not an interger, deliver first page.
        elements = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        elements = paginator.page(paginator.num_pages)
        
    print(elements)

    
    # return HttpResponse("Hello you are late you better hurry up !")
    return render(request, "film/base.html", {'films': films, 'elements': elements})

def film_detail(request, film_id):
    # add_movies()
    personal = user_movie_recommender(request)
    print(personal)
    
    movie = get_object_or_404(FilmSerie, id=film_id)
    
    film = get_movies_details(film_id)
    films = FilmSerie.objects.get(title = film['title'])
    comments =Comment.objects.filter(film=movie)
    
    movie = get_object_or_404(FilmSerie, id=film_id)
    recommendations = movie_recommender(film_id)
    print("-----------------------------       NEXT    ----------------------------------------")
    print(recommendations)
    
    user_rating = Rating.objects.filter(user=request.user, film=movie).first()

    if user_rating:
        form = RatingForm({'stars': user_rating.stars})
    else:
        form = RatingForm()

    average_rating = movie.ratings.aggregate(Avg('stars'))['stars__avg']
    
    context = {
        'movie': movie,
        'film' : film,
        'comments': comments,
        'recommendations': recommendations,
        'personals': personal
    }

    
    return render(request, 'film/detail.html', context)

def search(request):
    if request.method == 'GET':
        form = request.GET.get('search')

        if form:
            # query = form.cleaned_data['query']
            films = FilmSerie.objects.filter(title__icontains=form)
            #movie = get_object_or_404(FilmSerie, id=films['id'])
            # recommendations = movie_recommender(films.get(id))
            # for film in films:
            #     movie = get_object_or_404(FilmSerie, id=film.id)
            #     recommendations = movie_recommender(film.id)

            return render(request, 'film/result.html', {'movies': films, 'form': form})
        else:
            films = FilmSerie.objects.all()
        
            # return HttpResponse("Hello you are late you better hurry up !")
            return render(request, "film/base.html", {'films': films})
        
@login_required
def ajouter_film(request, film_id):
    film = FilmSerie.objects.get(id=film_id)
    panier, _ = Panier.objects.get_or_create(user=request.user)
    panier.films.add(film)
    messages.success(request, f"{film.title} a été ajouté à votre panier.")
    return redirect('film:liste_films_panier')

@login_required
def liste_films_panier(request):
    panier_exists = Panier.objects.filter(user=request.user).exists()
    if not panier_exists:
        panier = Panier.objects.create(user=request.user)
    else:
        panier = Panier.objects.get(user=request.user)

    liste_films = panier.films.all()
    context = {'liste_films': liste_films}
    return render(request, 'film/panier.html', context)

@login_required
def supprimer_film_panier(request, film_id):
    
    movie = get_object_or_404(FilmSerie, id=film_id)
    print("panier_1")
    
    if request.method == "POST":
        print("panier_2")
        panier = Panier.objects.get(user=request.user)
        if not request.user == panier.user:
            return HttpResponseForbidden()
        
        film_exists = panier.films.filter(id=film_id).first()
        if film_exists:
            print("panier_3")
            panier.films.remove(movie)
            messages.success(request, f"{movie.title} a été supprimé du panier.")
        else:
            messages.error(request, f"{movie.title} n'est pas dans le panier.")


    return redirect('film:liste_films_panier')

@login_required
def creer_collection(request):
    print("collec_1")
    panier = Panier.objects.get(user=request.user)
    print("collec_2")
    if request.method == 'POST':
        print("collec_3")
        nom = request.POST.get('nom_collection')
        success = False

        
        if Collection.objects.filter(user=request.user, nom=nom).exists():
            message = 'Vous avez déjà créé une collection avec ce nom.'
        else:

            films = panier.films.all()
            collection = Collection.objects.create(user=request.user, nom=nom)
            print("collec_4")
            for film in films:
                collection.films.add(film)
                print("collec_5")
            
            print("collec_6")
            panier.films.clear()
            print("collec_7")
            success = True
            messages.success(request, f"Collection {nom} créée avec succès !")
            print("collec_8")
            return redirect('film:liste_collections')
    else:
        messages.error(request, "Veuillez entrer un nom de collection valide.")
    print("collec_9")

    context = {'panier': panier, 'success': success, 'message': message}
    return render(request, 'film/collection.html', context)

@login_required
def liste_collections(request):
    collections = Collection.objects.filter(user=request.user)
    context = {'collections': collections}
    return render(request, 'film/collection.html', context)

@login_required
def supprimer_collection(request, nom):
    collection = Collection.objects.filter(user=request.user, nom=nom).first()
    if not request.user == collection.user:
        return HttpResponseForbidden()
    collection.delete()
    messages.success(request, f"Collection {collection.nom} supprimée avec succès.")
    return redirect('film:liste_collections')


@login_required
def ajouter_commentaire(request, film_id):
    movie = get_object_or_404(FilmSerie, id=film_id)
    parent_comment_id = request.POST.get('parent_comment_id') 

    if request.method == 'POST':
        content = request.POST.get('commentaire')
        parent_comment = None
        if parent_comment_id:
            parent_comment = Comment.objects.get(id=parent_comment_id)
        Comment.objects.create(user=request.user, film=movie, content=content, parent_comment=parent_comment)
        messages.success(request, 'Votre commentaire a été ajouté avec succès.')
        return redirect('film:film_detail', film_id=film_id)

    context = {
        'film': movie,
        'form': content,
    }
    return render(request, 'film/detail.html', context)

@login_required
def ajouter_note(request, film_id):
    film = get_object_or_404(FilmSerie, id=film_id)
    user_rating = Rating.objects.filter(user=request.user, film=film).first()

    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            stars = form.cleaned_data['stars']

            if user_rating:
                user_rating.stars = stars
                user_rating.save()
            else:
                Rating.objects.create(user=request.user, film=film, stars=stars)

            messages.success(request, 'Votre note a été enregistrée.')
            return redirect('film:detail_film', film_id=film_id)
    else:
        if user_rating:
            form = RatingForm({'stars': user_rating.stars})
        else:
            form = RatingForm()

    context = {
        'film': film,
        'form': form,
    }
    return render(request, 'film/ajouter_note.html', context)

film/templates/film/collection.html
{% extends "film/layout.html" %}

{% block content %}
  <h1>Mes collections</h1>
  <ul>
    {% for collection in collections %}
      <ol><h2>{{ collection.nom }} <a href="{% url 'film:supprimer_collection' nom=collection.nom %}">(supprimer)</a></h2></ol>
      <ul>
        <div class="row mt-5 row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 g-3" style="display: grid; grid-template-columns: repeat(4, 1fr);">
        {% for film in collection.films.all %}
        <div class="col-md-3" style="display: grid; grid-template-columns: repeat(4, 1fr);">
          <div class="card text-center h-100" style="width: 13rem;">
              <img src="https://image.tmdb.org/t/p/w200{{ film.poster_path }}" class="card-img-top" alt="{{ film.title }}">
              <div class="card-body">
              <a class="card-text" href="{% url 'film:film_detail' film_id=film.id %}"> {{ film.title }} </a>
          </div>
          </div>
      <div class="spacer"></div>
  </div>
        {% empty %}
          <li>Cette collection ne contient aucun film.</li>
        {% endfor %}
</div>
      </ul>
    {% empty %}
      <li>Vous n'avez encore créé aucune collection.</li>
    {% endfor %}
  </ul>
{% endblock content %}

film/templates/film/creation.html
{% extends "film/layout.html" %}

{% block content %}
<h1>Creer une Collection...</h1>

<div class="row">
    <div class="col-md-8">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="nom">Nom de la collection:</label>
          <input type="text" class="form-control" id="nom" name="nom" required>
        </div>
        <button type="submit" class="btn btn-primary">Créer</button>
      </form>
    </div>
  </div>



{% endblock %}

film/templates/film/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} FILM RECOMMENDER {% endblock %}</title>


        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'film/css/bootstrap.min.css' %}">
        
        <link rel="stylesheet" type="text/css" href="{% static 'film/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'registration/style.css' %}">
        <script type="text/javascript" src="{% static 'film/search.js' %}"></script>
        <script type="text/javascript" src="{% static 'registration/search.js' %}"></script>



        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script> 
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script> 

        <style>
          .nav-item {
            margin-right: 20px; /* adjust the margin to your liking */
  
          }
          .nav-link {
            display: inline-block;
            padding: 0 10px; /* add some padding to the links */
            border: none;
          }
        </style>

        <style>
          .navbar-nav {
            display: flex;
            gap: 40px; /* add a gap of 20px between each item */
            border: none;
          }
          #account {
            padding-left: 20px;
            padding-top: -150px;
            gap: 10px;
            border: none;
            /* border: 1px solid #fcf6f6; */
        }

        #list_de_genre {
          border: none;
      }
      
      #ma_list {
        border: none;
        font-size: 100%;

      }
      #title {
        border: none;
        color: white;
    }

    #stars {
      color: white; /* sets the color of the link */
      text-decoration: none; /* removes the underline from the link */
      stroke: gold;
      fill: white;
    }
    
    #stars:hover {
      color: gold;
      fill: gold; /* sets the color of the link when hovered over */
    }

    .bi-star {
      fill: #ccc; /* default color */
    }
  
    .bi-star:hover {
      fill: #ffd700; /* hover color */
    }
  
    .bi-star:hover ~ .bi-star {
      fill: #ccc; /* reset color for subsequent stars */
    }
  
    .bi-star:hover ~ .bi-star:hover {
      fill: #ffd700; /* hover color for previous stars */
    }
        </style>

        <script>
          $(document).ready(function(){
            $('#list_de_genre').on('click', function(){
              $(this).find('.dropdown-menu').toggle();
            });
          });

          $(document).ready(function(){
            $('#list_de_genre .dropdown-item').on('click', function(){
              var selectedValue = $(this).data('value');
              $('#navbarDarkDropdownMenuLink').text(selectedValue);
            });
          });

          document.addEventListener("DOMContentLoaded", function() {
            var myModal = new bootstrap.Modal(document.getElementById("myModal"));
          });

          $(function() {
            $('.reply-link').click(function() {
              var parent_id = $(this).data('parent');
              $('#parent_comment_id').val(parent_id);
              window.location.href = '#ajouter_commentaire';
            });
          });
          
          $(document).ready(function() {
            $('a[id="stars"]').hover(function() {
              var value = $(this).attr('value');
              $('a[id="stars"][value="' + value + '"]').prevAll('a[id="stars"]').find('.bi-star').css('fill', '#ffd700');
            }, function() {
              $('a[id="stars"]').find('.bi-star').css('fill', '#ccc');
            });
          });

      </script>

    </head>

    <body class="body">
        <nav class="navbar navbar-expand-lg navbar-orange mx-auto">
            <div class="container-fluid mx-auto">

                <a class="navbar-brand" href="#" id="title">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-tv-fill h-500 w-1500" viewBox="0 0 16 16">
                    <path d="M2.5 13.5A.5.5 0 0 1 3 13h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5M2 2h12s2 0 2 2v6s0 2-2 2H2s-2 0-2-2V4s0-2 2-2"/>
                  </svg><b> FILM RECOMMENDER</b> </a>
            
            </div>

            <div class="container">

                <form action="{% url 'film:movie_search' %}" method="get" class="d-flex" id="search-form">

                <input class="form-control mr-sm-2 search-box" type="search" placeholder="Search for a film or a TV movie" name="search" value="{{ query }}" aria-label="Search" id="search-box" style="width: 300px;font-size: 75%;">
                <button class="btn btn-outline-sucess my-2 my-sm-0 btn-icon text-light " type="submit" id="search-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-search text-light" stroke="#0d6efd" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                      </svg> 
                </button>
                
                </form>
            
            </div>

            <div class="container">

                <div class="collapse navbar-collapse " id="navbarSupportedContent" >

                    <ul class="navbar-nav ml-auto">
                        
                        <li class="nav-item">

                            <a class="nav-link" href="{% url 'film:liste_films_panier' %}" id="ma_list" style="font-size: 100%">
                                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-play-btn-fill" viewBox="0 0 16 16" style="font-size: 75%;display: inline-block;">
                                    <path d="M0 12V4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2m6.79-6.907A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814z"/>
                                  </svg>
                                Ma Liste
                            </a>
                        </li>

                        <li class="nav-item">
                            <div class="container-fluid">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="False" aria-label="Toggle navigation">
                                  <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                  <ul class="navbar-nav" id="list_de_genre">
                                    <li class="nav-item dropdown">
                                      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Film/Series
                                      </a>
                                      <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDarkDropdownMenuLink">
                                        <li><a class="dropdown-item" href="{% url 'film:homepage' %}" data-value="Film">Film</a></li>
                                        <li><a class="dropdown-item" href="#" data-value="Series">Series</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#" data-value="Film/Series">Film/Series</a></li>
                                      </ul>
                                    </li>
                                  </ul>
                                </div>
                            </div>
                            
                        </li>

                        <li class="nav-item" id="account">
                            
                            {% if user.is_authenticated %}

                            <div class="container-fluid">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                  <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                  <ul class="navbar-nav" id="utilisateur">
                                    <li class="nav-item dropdown">
                                      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ user.username }} 
                                      </a>
                                      <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDarkDropdownMenuLink">
                                        <li><a class="dropdown-item" href="{% url 'film:liste_collections' %}">Mes Collections</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="{% url 'reg:logout' %}">Deconexion</a></li>
                                      </ul>
                                    </li>
                                  </ul>
                                </div>
                            </div>
                            {% else %}
                            <a class="nav-link" href="{% url 'reg:login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16" style="align-content: flex-end;">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                            </svg></a>

                            {% endif %}

                            {% comment %} {% block user %}  {% endblock user %} {% endcomment %}

                        </li>

                    </ul>

                </div>

            </div>
            
        </nav>
        <script src="{% static 'film/js/bootstrap.min.js' %}"></script>
        <script>
            $(document).ready(function(){
                $('#search-btn').popover({
                    trigger: 'manual',
                    title: 'Error',
                    content: 'Please enter a search term'
                });
            
                function togglePopover() {
                    var searchTerm = $('#search-box').val().trim();
                    if (searchTerm === '') {
                        $('#search-btn').popover('show');
                    } else {
                        $('#search-btn').popover('hide');
                    }
                }
            
                $('#search-box').on('keyup', togglePopover);
            });
          </script>
        {% block content%}{% endblock %}

    </body>

</html>

film/templates/film/panier.html
{% extends "film/layout.html" %}

{% block content %}
<h1>Ma liste de films ajoutés</h1>

    <div class="row mt-5 row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 g-3" style="display: grid; grid-template-columns: repeat(4, 1fr);">
  {% for film in liste_films %}
  <div class="col-md-3">
                <div class="card text-center h-100" style="width: 13rem;">
                    <img src="https://image.tmdb.org/t/p/w200{{ film.poster_path }}" class="card-img-top" alt="{{ film.title }}">
                    <div class="card-body">
                    <a class="card-text" href="{% url 'film:film_detail' film_id=film.id %}"> {{ film.title }} </a>
                    <form method="POST" action="{% url 'film:supprimer_film_panier' film_id=film.id %}"> {% csrf_token %} <input type="hidden" name="movie_id" value="{{ film.movie.id }}"> <button class="btn btn-danger">Retirer</button> </form>
                </div>
                </div>
            <div class="spacer"></div>
        </div>
  {% empty %}
    <p>Votre liste de films est vide</p>
  {% endfor %}


<div class="position-fixed bottom-0 end-0 p-1">
    <button type="button" class="btn btn-primary btn-lg rounded-circle" data-bs-toggle="modal" data-bs-target="#myModal" data-bs-toggle="tooltip" data-bs-placement="top" title="Creer une nouvelle Collection !" >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-collection-play-fill" viewBox="0 0 16 16">
            <path d="M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6zm6.258-6.437a.5.5 0 0 1 .507.013l4 2.5a.5.5 0 0 1 0 .848l-4 2.5A.5.5 0 0 1 6 12V7a.5.5 0 0 1 .258-.437"/>
          </svg>

    </button>
</div>

<!-- The modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        {% if success %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% elif message %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% endif %}


        <!-- The form inside the modal -->
        <form method="POST" action="{% url 'film:creer_collection' %}">
          {% csrf_token %}  <!-- CSRF token for security -->
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nom de votre Collection</label>
            <input type="text" class="form-control" name="nom_collection" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Veuillez choisir un nom qui vous convient..</div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

film/templates/film/result.html
{% extends "film/layout.html" %}

{% block content %}

<div class="row mt-5">
    {% if movies %}
    <h3>Resultat de : {{ form.upper }}</h3>
    <hr>
        {% for film in movies %}
        <div class="col-md-3">
                <div class="card text-center h-100" style="width: 13rem;">
                    <img src="https://image.tmdb.org/t/p/w200{{ film.poster_path }}" class="card-img-top" alt="{{ film.title }}">
                    <div class="card-body">
                    <a class="card-text" href="{% url 'film:film_detail' film_id=film.id %}"> {{ film.title }} </a>
                </div>
                </div>
            <div class="spacer"></div>
        </div>
        {% endfor %}
        <hr>
    {% else %}
    <hr>
    <h3>Resultat de : {{ form.upper }}</h3>
    <h1> Ce mot ne correspond a aucun film. Veuillez verifier l'orthographe et reesayer... </h1>
     {% endif %}
</div>
{% endblock %}